### ISSUE TITLE
7天会员功能在1.4.4;1.4.5版本测试无效

### ISSUE THREAD

**Issue by popdog0** [oureveryday/PikPakBypass#2]
7天会员功能在1.4.4;1.4.5版本测试无效

**Comment by oureveryday** [comment]
1. 请每次注册账号前运行 `Clear.bat` 以清除数据
2. 有几率注册不获得会员，需要重新注册（如果还剩不行请更换临时邮箱网站）
3. Pikpak近期关闭了PC端会员获取通道，故只能获取4天会员，并且注册后无法看到会员生效，需重启才可看到。
