### ISSUE TITLE
为什么不运行呢

### ISSUE THREAD

**Issue by railgun0325** [oureveryday/PikPakBypass#5]
![image](https://github.com/user-attachments/assets/526881ea-d608-496f-b8fe-8144a7e740b2)
打开pikpak的网页之后没有运行脚本

**Comment by oureveryday** [comment]
这个是用于Windows客户端的，不是网页版的

**Comment by railgun0325** [comment]
谢谢您的回复，我是说按照文件中“PikPak开发者工具【By纸鸢花的花语】”pdf中的教程安装的油猴脚本无法在网页端运行。
![image](https://github.com/user-attachments/assets/a7260a5b-e9aa-4b12-a608-016ef2ed2229)

不好意思，刚刚发现问题了，已经解决了。不知道咋的把chrome开发者模式关掉了😂。

**Comment by railgun0325** [comment]
但是那个桌面端按照您的方法修改之后依然有问题如下
![image](https://github.com/user-attachments/assets/7aa386dc-acb3-49a9-abcd-a2218967bce7)
就是国内会员，海外使用会受限。我用以下脚本可以在网页端解决这个问题，但是桌面端就没有办法了。
![image](https://github.com/user-attachments/assets/0aa577d5-ef4e-4024-b48e-20e2193cb319)
![image](https://github.com/user-attachments/assets/c9036161-bb53-40b4-b089-f6046f1f3b8a)

**Comment by railgun0325** [comment]
可能是clear.bat没有运行成功的问题？我把bat文件拖到pikpak目录下之后运行，显示如下
![image](https://github.com/user-attachments/assets/77a65f60-78bc-4012-910f-1785a3010a8b)

**Comment by oureveryday** [comment]
ip问题，我不解决
